// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvmcsbezqqapkjsdxwly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2bWNzYmV6cXFhcGtqc2R4d2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODA2MDEsImV4cCI6MjA2OTM1NjYwMX0.bhdD9-XyCkMTJj4QXliHZIOF2FWnOEMKNrA50fmOGSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});